# Generated by Django 5.1.1 on 2024-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="descr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
